app:
  port: "8080"
  logLevel: "info"

database:
  type: "postgres"
  connectionString: "host=our-cloudsql-instance-ip dbname=our-database-name user=our-database-user password=our-database-password sslmode=disable"

cloudStorage:
  bucketName: "our-gcs-bucket-name"
  credentialsPath: "/path/to/our/google-credentials.json"

projectID: "our-google-cloud-project-id"  # Google Cloud Project ID
locationID: "our-google-cloud-location-id"  # Google Cloud Location ID

validApiKeys:
    - "api-key-4532"
    - "api-key-7524"

dataSources:
  satellite:
    enabled: true
    schedule: "0 */6 * * *"
    timeZone: "UTC"
    httpMethod: "GET"
    endpoint: "https://api.nasa.gov/planetary/earth/assets?lon={lon}&lat={lat}&date={date}&dim=0.10&api_key={apiKey}"
    apiKey: "our-nasa-api-key"
    description: "Regular retrieval of satellite data providing high-resolution earth imagery for vineyard analysis."

  eosdis:
    enabled: true
    schedule: "0 12 * * *"
    timeZone: "UTC"
    httpMethod: "GET"
    endpoint: "https://worldview.earthdata.nasa.gov/?t={date}T00:00:00Z&l=MODIS_Aqua_CorrectedReflectance_TrueColor,Coastlines&z=3&v={lonLeft},{latBottom},{lonRight},{latTop}"
    description: "Daily monitoring of global satellite data for environmental impacts on vineyard health."

  skywatch:
    enabled: true
    schedule: "5 15 * * 1"
    timeZone: "UTC"
    httpMethod: "GET"
    endpoint: "https://api.skywatch.co/data/earthcache?geometry={polygon}&start={startDate}&end={endDate}&resolution=min&api_key={apiKey}"
    apiKey: "our_skywatch_api_key"
    description: "Weekly ingestion of advanced multispectral imagery for detailed analysis of vineyard conditions."

  eosdaLandViewer:
    enabled: true
    schedule: "0 0 1 * *"
    timeZone: "UTC"
    httpMethod: "GET"
    endpoint: "https://api.eos.com/v1/landviewer/{polygon}?start_date={startDate}&end_date={endDate}&api_key={apiKey}"
    apiKey: "our_eosda_api_key"
    description: "Monthly updates from Land Viewer for land cover and use analysis vital for long-term planning."

  soil:
    enabled: true
    schedule: "0 */12 * * *"
    timeZone: "UTC"
    httpMethod: "GET"
    endpoint: "https://api.soilgrids.org/query?lat={lat}&lon={lon}"
    apiKey: "our-soilgrids-api-key"
    description: "Twice-daily soil data retrieval for precise nutrient and moisture analysis."

  weather:
    enabled: true
    schedule: "0/30 * * * *"
    timeZone: "UTC"
    httpMethod: "GET"
    endpoint: "https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={apiKey}"
    apiKey: "our-openweathermap-api-key"
    description: "Continuous updates of weather conditions to aid in immediate vineyard management decisions."

  databaseCleanup:
    enabled: true
    schedule: "0 0 * * 0"
    timeZone: "UTC"
    httpMethod: "POST"
    endpoint: "https://foo.com/api/v1/maintenance/db_cleanup"
    description: "Routine database maintenance to ensure optimal performance and data integrity."

  reportGeneration:
    enabled: true
    schedule: "0 2 * * 0"
    timeZone: "UTC"
    httpMethod: "POST"
    endpoint: "https://foo.com/api/v1/report/generate"
    description: "Automated weekly generation of reports to analyze vineyard health and productivity trends."

  systemHealthCheck:
    enabled: true
    schedule: "*/15 * * * *"
    timeZone: "UTC"
    httpMethod: "GET"
    endpoint: "https://foo.com/api/v1/system/health"
    description: "Regular system checks to ensure all components are functioning and responsive."

ingestionSettings:
  retryPolicy:
    maxRetries: 3
    backoffInterval: "30s"
  parallelIngestions: 5

notifications:
  emailService:
    enabled: true
    SMTPHost: "smtp.foo.com"
    SMTPPort: 587
    Username: "email@foo.com"
    Password: "our-password"
    FromEmail: "no-reply@foo.com"

